# Generated by Django 3.2.25 on 2026-07-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'تماس', 'verbose_name_plural': 'تماس ها'},
        ),
    ]
